default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: posts_development

test:
  <<: *default
  database: posts_test

production:
  <<: *default
  database: posts_production
  username: posts
  password: <%= ENV['POSTS_DATABASE_PASSWORD'] %>
